name: 3 - Static Files for Django

# Controls when the workflow will run
on:
  # Allows you to call this workflow within another workflow
  workflow_call:
      secrets:
        LINODE_BUCKET:
          required: true
        LINODE_BUCKET_REGION:
          required: true
        LINODE_BUCKET_ACCESS_KEY:
          required: true
        LINODE_BUCKET_SECRET_KEY:
          required: true
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  django_staticfiles:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Add in environment variables for the entire "build" job
    env:
      GITHUB_ACTIONS: true
      DATABASE_BACKEND: mysql
      DJANGO_SECRET_KEY: just-a-test-database
      DJANGO_STORAGE_SERVICE: linode
      LINODE_BUCKET: ${{ secrets.LINODE_BUCKET }}
      LINODE_BUCKET_REGION: ${{ secrets.LINODE_BUCKET_REGION }}
      LINODE_BUCKET_ACCESS_KEY: ${{ secrets.LINODE_BUCKET_ACCESS_KEY }}
      LINODE_BUCKET_SECRET_KEY: ${{ secrets.LINODE_BUCKET_SECRET_KEY }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install requirements
        run: |
          pip install -r requirements.txt
      - name: Collect Static
        run: |
          python manage.py collectstatic --noinput